CREATE TABLE Admin (id SERIAL PRIMARY KEY,nama VARCHAR(255) NOT NULL,username VARCHAR(50) NOT NULL,password VARCHAR(255) NOT NULL);

CREATE TABLE articles (id SERIAL PRIMARY KEY,title VARCHAR(255) NOT NULL,content JSON NOT NULL,writer_id INTEGER REFERENCES writer(id),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);

CREATE TABLE tags (id SERIAL PRIMARY KEY,name VARCHAR(50) NOT NULL);

CREATE TABLE article_tags (article_id INTEGER REFERENCES articles(id),tag_id INTEGER REFERENCES tags(id),PRIMARY KEY (article_id, tag_id));

ALTER TABLE writer ADD admin_id INTEGER REFERENCES Admin(id);

CREATE TABLE articles_draft (article_id INT UNIQUE REFERENCES articles(id),title VARCHAR(255) NOT NULL,content JSON NOT NULL,writer_id INTEGER REFERENCES writer(id),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);

CREATE TABLE articles_header (article_id INT UNIQUE REFERENCES articles(id),title VARCHAR(255) NOT NULL,header JSON NOT NULL,writer_id INTEGER REFERENCES writer(id),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);

ALTER TABLE articles_draft ADD status BOOLEAN;

CREATE TABLE Gambar (id SERIAL PRIMARY KEY, name_image VARCHAR(255) NOT NULL,url_image VARCHAR(255) NOT NULL);

ALTER TABLE articles_draft ADD url_image VARCHAR(255);

ALTER TABLE articles ADD url_image VARCHAR(255);

ALTER TABLE articles ADD Descrip VARCHAR(255);

ALTER TABLE articles_draft ADD Descrip VARCHAR(255);

CREATE TABLE ads (id SERIAL PRIMARY KEY,ads_name VARCHAR(255) NOT NULL,content JSON NOT NULL,admin_id INTEGER REFERENCES admin(id),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);

CREATE TABLE ads_tags (ads_id INTEGER REFERENCES ads(id),tag_id INTEGER REFERENCES tags(id),PRIMARY KEY (ads_id, tag_id));

CREATE TABLE ads_image (id SERIAL PRIMARY KEY, name_image VARCHAR(255) NOT NULL,url_image VARCHAR(255) NOT NULL, admin_id INTEGER REFERENCES admin(id));